language: node_js
node_js:
  - "lts/*"
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE hotmeal;" -U postgres
  - psql -c "CREATE USER hotmealuser WITH PASSWORD '1';" -U postgres  
  - "npm run build:db && npm run build:static" 
env: 
  global: 
  - PGPORT=5432
test: 
  adapter: postgresql
  database: hotmeal

  